package projekt_mpr.dao;

import java.sql.*;
import java.util.ArrayList;

import projekt_mpr.dao.mappers.ResultSetMapper;
import projekt_mpr.domain.Accessory;


public class AccessoryRepository extends RepositoryBase<Accessory>{
	
	public AccessoryRepository(ResultSetMapper <Accessory> mapper){
		super(mapper);
	}
	@Override
	protected String createTableSql() {
		return "CREATE TABLE accessories("
				+ "id INT GENERATED BY DEFAULT AS IDENTITY,"
				+ "name VARCHAR(20),"
				+ "price FLOAT(6,2)"
				+ ")";
	}
	@Override
	protected String insertSql() {
		return "INSERT INTO accessories(name,price) VALUES (?,?)";
	}
	@Override
	protected String updateSql() {
		return "UPDATE accessories SET (name, price) = (?,?) WHERE id=?";
	}
	@Override
	protected String deleteSql() {
		return "DELETE FROM accessories WHERE id=?";
	}
	@Override
	protected String selectAllSql() {
		return "SELECT * FROM accessories";
	}
	@Override
	protected String tableName() {
		return "accessories";
	}
	@Override
	protected void parametrizeUpdateStatement(PreparedStatement statement, Accessory accessory) throws SQLException {
		statement.setString(1, accessory.getName());
		statement.setFloat(2, accessory.getPrice());
		statement.setInt(3, accessory.getId());
		
	}
	@Override
	protected void parametrizeInsertStatement(PreparedStatement statement, Accessory accessory) throws SQLException {
		statement.setString(1, accessory.getName());
		statement.setFloat(2, accessory.getPrice());
		
	}
}
