package projekt_mpr.dao;

import java.sql.*;
import java.util.ArrayList;

import projekt_mpr.dao.mappers.ResultSetMapper;
import projekt_mpr.domain.Customer;


public class CustomerRepository extends RepositoryBase<Customer>{

	public CustomerRepository(Connection connection, ResultSetMapper<Customer> mapper) throws SQLException {
			super(connection, mapper);
	}
	@Override
	protected String createTableSql() {
		return"CREATE TABLE customers("
			+"id INT GENERATED BY DEFAULT AS IDENTITY, "
			+"name VARCHAR(20), "
			+"surname VARCHAR(30), "
			+"address VARCHAR(50)" 
			+")";
	}
	@Override
	protected String insertSql() {
		return "INSERT INTO customers(name, surname, address) VALUES(?,?,?)";
	}
	@Override
	protected String updateSql() {
		return "UPDATE customers SET (name, surname, address)=(?,?,?) WHERE id=?";
	}
	@Override
	protected String deleteSql() {
		return "DELETE FROM customers WHERE id=?";
	}
	@Override
	protected String selectAllSql() {
		return "SELECT * FROM customers";
	}
	@Override
	protected String tableName() {
		return "customers";
	}
	@Override
	protected void parametrizeUpdateStatement(PreparedStatement statement, Customer customer) throws SQLException {
		statement.setString(1, customer.getName());
		statement.setString(2, customer.getSurname());
		statement.setString(3, customer.getAddress());
		statement.setInt(4, customer.getId());
	}
	@Override
	protected void parametrizeInsertStatement(PreparedStatement statement, Customer customer) throws SQLException {
		statement.setString(1, customer.getName());
		statement.setString(2, customer.getSurname());
		statement.setString(3, customer.getAddress());
	}
}