package projekt_mpr.dao;

import java.sql.*;
import java.util.ArrayList;

import projekt_mpr.dao.mappers.ResultSetMapper;
import projekt_mpr.domain.Fertilizer;

public class FertilizerRepository extends RepositoryBase<Fertilizer> {

	public FertilizerRepository(ResultSetMapper<Fertilizer> mapper) {
		super(mapper);
	}
	@Override
	protected String createTableSql() {
		return "CREATE TABLE fertilizers("
				+ "id INT GENERATED BY DEFAULT AS IDENTITY, "
				+ "name VARCHAR(20), "
				+ "manufacturer VARCHAR(30), "
				+ "price FLOAT(6,2)"
				+ ")";
	}
	@Override
	protected String insertSql() {
		return "INSERT INTO fertilizers(name, manufacturer, price) VALUES (?,?,?)";
	}
	@Override
	protected String updateSql() {
		return "UPDATE fertilizers SET (name, manufacturer, price) =(?,?,?) WHERE id=?";
	}
	@Override
	protected String deleteSql() {
		return "DELETE FROM fertilizers WHERE id =?";
	}
	@Override
	protected String selectAllSql() {
		return "SELECT * FROM fertilizers";	
	}
	@Override
	protected String tableName() {
		return "fertilizers";
	}
	@Override
	protected void parametrizeUpdateStatement(PreparedStatement statement, Fertilizer fertilizer) throws SQLException {
		statement.setString(1, fertilizer.getName());
		statement.setString(2, fertilizer.getManufacturer());
		statement.setFloat(3, fertilizer.getPrice());
		statement.setInt(4, fertilizer.getId());
	}
	@Override
	protected void parametrizeInsertStatement(PreparedStatement statement, Fertilizer fertilizer) throws SQLException {
		statement.setString(1, fertilizer.getName());
		statement.setString(2, fertilizer.getManufacturer());
		statement.setFloat(3, fertilizer.getPrice());
	}
}